dbt_example:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: future-loader-463405-i5
      dataset: dbt_dw  # ou use 'schema' se for BigQuery antigo
      threads: 4
      keyfile: /home/raphaeleng/.dbt/future-loader-463405-i5-bb0a84fe4fe4.json
